/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI_Fournisseur;

import GUI_Produit.*;
import GUI.*;
import entity.Fournisseur;
import entity.Produit;
import java.sql.Date;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class AjouterFournisseur extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterProduit
     */
    public AjouterFournisseur() {
        initComponents();
        this.setSize(791, 680);
        
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAddProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPRENOM = new javax.swing.JTextField();
        jNOM = new javax.swing.JTextField();
        jTYPEPROD = new javax.swing.JTextField();
        jValider = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jreturn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1111, 107));

        jpAddProd.setBackground(new java.awt.Color(229, 229, 250));
        jpAddProd.setPreferredSize(new java.awt.Dimension(757, 111));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Ajouter un Fournisseur");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Nom  :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Type Produits :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Prénom :");

        jPRENOM.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPRENOM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPRENOM.setText(" ");
        jPRENOM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jNOM.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jNOM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNOM.setText(" ");
        jNOM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTYPEPROD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTYPEPROD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTYPEPROD.setText(" ");
        jTYPEPROD.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jValider.setBackground(new java.awt.Color(255, 255, 255));
        jValider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jValider.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\save3.png")); // NOI18N
        jValider.setText("Enregistrer");
        jValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderActionPerformed(evt);
            }
        });

        jReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\rese1.png")); // NOI18N
        jReset.setText("Réinitialiser");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jreturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jreturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpAddProdLayout = new javax.swing.GroupLayout(jpAddProd);
        jpAddProd.setLayout(jpAddProdLayout);
        jpAddProdLayout.setHorizontalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jreturn)
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(569, Short.MAX_VALUE))
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addComponent(jPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addComponent(jNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddProdLayout.createSequentialGroup()
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpAddProdLayout.createSequentialGroup()
                                .addComponent(jTYPEPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpAddProdLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jReset)
                                    .addComponent(jValider, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
        );
        jpAddProdLayout.setVerticalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTYPEPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jValider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int cmp=1;
    private void jValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderActionPerformed
    
        Fournisseur.lp=Fournisseur.getFournisseur();
        for(int i=0;i<Fournisseur.lp.size();i++){
            cmp=Fournisseur.lp.get(i).idFournisseur+1;
        }
        int idF = cmp;

        String nom = jNOM.getText();
        
        String prenom = jPRENOM.getText();
        
        String typeProd = jTYPEPROD.getText();
        
        Fournisseur c=new Fournisseur(idF,nom,prenom,typeProd);

        JOptionPane jp=new JOptionPane();

        if(nom.equals("") && prenom.equals("") && typeProd.equals("")){

            jp.showMessageDialog(this,"Erreur Veuillez saisir les informations","Erreur",JOptionPane.ERROR_MESSAGE);
        }

        else{

            boolean res=Fournisseur.CreateFournissueur(c);

            if(res==true){
                JOptionPane.showMessageDialog(this, "Fournisseur ajouté avec succès", "Bravo", JOptionPane.INFORMATION_MESSAGE);
                 this.setVisible(false);
                System.out.println("done");

            }

        }
                                      
    }//GEN-LAST:event_jValiderActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        jNOM.setText("");
        jPRENOM.setText("");
        jTYPEPROD.setText("");
    }//GEN-LAST:event_jResetActionPerformed

    private void jreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jreturnMouseClicked
        this.setVisible(false);
        //this.dispose();
        new interfaceFournisseur().setVisible(true);
    }//GEN-LAST:event_jreturnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNOM;
    private javax.swing.JTextField jPRENOM;
    private javax.swing.JButton jReset;
    private javax.swing.JTextField jTYPEPROD;
    private javax.swing.JButton jValider;
    private javax.swing.JPanel jpAddProd;
    private javax.swing.JLabel jreturn;
    // End of variables declaration//GEN-END:variables
}
