/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI_Fournisseur;

import GUI_Produit.*;
import GUI.*;
import entity.Fournisseur;
import entity.Produit;
import java.sql.Date;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class ModifierFournisseur extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterProduit
     */
    public ModifierFournisseur() {
        initComponents();
        this.setSize(791, 680);
        
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAddProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPRENOMFOUR = new javax.swing.JTextField();
        jNOMFOUR = new javax.swing.JTextField();
        jTYPEPROD = new javax.swing.JTextField();
        jValider = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jRETURN = new javax.swing.JLabel();
        jIDMOD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1111, 107));

        jpAddProd.setBackground(new java.awt.Color(229, 229, 250));
        jpAddProd.setPreferredSize(new java.awt.Dimension(757, 111));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Modifier les informations d'un fournisseur");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Nom  :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Type des produits: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Prénom :");

        jPRENOMFOUR.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPRENOMFOUR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPRENOMFOUR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jNOMFOUR.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jNOMFOUR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNOMFOUR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTYPEPROD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTYPEPROD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTYPEPROD.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jValider.setBackground(new java.awt.Color(255, 255, 255));
        jValider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jValider.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\save3.png")); // NOI18N
        jValider.setText("Enregistrer");
        jValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderActionPerformed(evt);
            }
        });

        jReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\rese1.png")); // NOI18N
        jReset.setText("Réinitialiser");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jRETURN.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jRETURN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRETURNMouseClicked(evt);
            }
        });

        jIDMOD.setBackground(new java.awt.Color(255, 102, 102));
        jIDMOD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jIDMOD.setForeground(new java.awt.Color(255, 255, 255));
        jIDMOD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jIDMOD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("ID du fournisseur à modifier:");

        javax.swing.GroupLayout jpAddProdLayout = new javax.swing.GroupLayout(jpAddProd);
        jpAddProd.setLayout(jpAddProdLayout);
        jpAddProdLayout.setHorizontalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRETURN)
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPRENOMFOUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTYPEPROD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNOMFOUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIDMOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jpAddProdLayout.setVerticalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIDMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNOMFOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPRENOMFOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTYPEPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addComponent(jRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jValider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderActionPerformed

    
          
        int id=Integer.parseInt(jIDMOD.getText()) ;
        
        String nomFournisseur = jNOMFOUR.getText();
        
        String prenomFournisseur = jPRENOMFOUR.getText();
        
        String typeProd = jTYPEPROD.getText();

        
        Fournisseur c = new Fournisseur(id, nomFournisseur, prenomFournisseur, typeProd);

        boolean res= Fournisseur.UpdateFournisseur(c, id);

        JOptionPane jp=new JOptionPane();

        if(res==true){
            jp.showMessageDialog(this,"Fournisseur modifié","Modification du fournisseur",JOptionPane.INFORMATION_MESSAGE);
            
        }

        else{
        jp.showMessageDialog(this,"Erreur Veuillez saisir les informations","Erreur",JOptionPane.ERROR_MESSAGE);
            

        }

        
                                      
    }//GEN-LAST:event_jValiderActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
       
        jIDMOD.setText("");
        jNOMFOUR.setText("");
        jPRENOMFOUR.setText("");
        jTYPEPROD.setText("");
    }//GEN-LAST:event_jResetActionPerformed

    private void jRETURNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRETURNMouseClicked
        this.setVisible(false);
         new interfaceFournisseur().setVisible(true);
    }//GEN-LAST:event_jRETURNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jIDMOD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNOMFOUR;
    private javax.swing.JTextField jPRENOMFOUR;
    private javax.swing.JLabel jRETURN;
    private javax.swing.JButton jReset;
    private javax.swing.JTextField jTYPEPROD;
    private javax.swing.JButton jValider;
    private javax.swing.JPanel jpAddProd;
    // End of variables declaration//GEN-END:variables
}
