/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI_Client;

import entity.Commande;
import GUI_Fournisseur.*;
import GUI_Produit.*;
import GUI.*;
import entity.Fournisseur;
import entity.Produit;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class FinaliserCommande extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterProduit
     */
    public FinaliserCommande() {
        initComponents();
        this.setSize(791, 680);
        
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
 
        jDATECOMM.setText(now());
       
    }
public static final String DateFormat = "yyyy-MM-dd";
public static String now(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat(DateFormat);
        return format.format(cal.getTime());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFinaliserCommande = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNOMCLIENT = new javax.swing.JTextField();
        jNOMCOM = new javax.swing.JTextField();
        jEffectCommande = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jQTE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDATECOMM = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1111, 107));

        jpFinaliserCommande.setBackground(new java.awt.Color(149, 205, 202));
        jpFinaliserCommande.setPreferredSize(new java.awt.Dimension(757, 111));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Finaliser ma commande");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("nom Client");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("nomCommande");

        jNOMCLIENT.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jNOMCLIENT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNOMCLIENT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jNOMCOM.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jNOMCOM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNOMCOM.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jEffectCommande.setBackground(new java.awt.Color(255, 255, 255));
        jEffectCommande.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEffectCommande.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\buy1.png")); // NOI18N
        jEffectCommande.setText("Commander");
        jEffectCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEffectCommandeActionPerformed(evt);
            }
        });

        jReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\rese1.png")); // NOI18N
        jReset.setText("Réinitialiser");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jQTE.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jQTE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQTE.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText("La quantité à commande");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("Date de la commande");

        jDATECOMM.setEditable(false);
        jDATECOMM.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jDATECOMM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDATECOMM.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        javax.swing.GroupLayout jpFinaliserCommandeLayout = new javax.swing.GroupLayout(jpFinaliserCommande);
        jpFinaliserCommande.setLayout(jpFinaliserCommandeLayout);
        jpFinaliserCommandeLayout.setHorizontalGroup(
            jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8)
                            .addGap(214, 214, 214)
                            .addComponent(jLabel1))
                        .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                            .addGap(273, 273, 273)
                            .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jQTE, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jNOMCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDATECOMM, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jNOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(550, Short.MAX_VALUE))
            .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFinaliserCommandeLayout.createSequentialGroup()
                        .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jEffectCommande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFinaliserCommandeLayout.createSequentialGroup()
                                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 854, Short.MAX_VALUE))))
        );
        jpFinaliserCommandeLayout.setVerticalGroup(
            jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEffectCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpFinaliserCommandeLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNOMCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQTE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(jpFinaliserCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jDATECOMM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 192, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFinaliserCommande, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFinaliserCommande, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int cmp=1;
    private void jEffectCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEffectCommandeActionPerformed
      int quantiteComander=Integer.parseInt(jQTE.getText());
        
        int qterestante=Voir_CommanderProduit.quantite-quantiteComander;
        
     
        
        JOptionPane jp=new JOptionPane();
        if(quantiteComander>qterestante){
                      
            jp.showMessageDialog(this,"Quantité indisponible !");
        
        }
        else{
            boolean res=Produit.updateQteProd(Voir_CommanderProduit.nomProd,qterestante);
//        if(res==true){
//            jp.showMessageDialog(this,"qte updated");
//        }
//        
//        else{
//            jp.showMessageDialog(this,"errorqte");
//        }
        int idClient = Commande.getIDClient(MainGUI.login, MainGUI.password);
        int idProd1 = Voir_CommanderProduit.idProd;
        String nomCommande=jNOMCOM.getText();
        
        String datecmd=jDATECOMM.getText();
        
        Date dateCOmmande=Date.valueOf(datecmd);
        
        String nomClient=jNOMCLIENT.getText();
        
        int pu=Produit.GetPU(Voir_CommanderProduit.nomProd);
        
        int prixTotal=quantiteComander*pu;
        
        Commande c=new Commande(idClient,idProd1 ,nomCommande,dateCOmmande,quantiteComander,nomClient,prixTotal);
        
        System.out.println(prixTotal);
        
        boolean res1=Commande.commander_prod(c);
        
        if(res1==true){
            jp.showMessageDialog(this,"Votre commande est ajoutée avec succès.","Bravo",JOptionPane.INFORMATION_MESSAGE);
        }
        
        else{
            jp.showMessageDialog(this,"Error");
        }
        }               
    
    }//GEN-LAST:event_jEffectCommandeActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
jNOMCLIENT.setText("");
jNOMCOM.setText("");
jQTE.setText("");
    }//GEN-LAST:event_jResetActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDATECOMM;
    private javax.swing.JButton jEffectCommande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNOMCLIENT;
    private javax.swing.JTextField jNOMCOM;
    private javax.swing.JTextField jQTE;
    private javax.swing.JButton jReset;
    private javax.swing.JPanel jpFinaliserCommande;
    // End of variables declaration//GEN-END:variables
}
