/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI_Produit;

import GUI.*;
import entity.Produit;
import java.sql.Date;
import java.text.SimpleDateFormat;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class ModifierProduit extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterProduit
     */
    public ModifierProduit() {
        initComponents();
        this.setSize(791, 680);
        
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAddProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPU = new javax.swing.JTextField();
        jNOMPROD = new javax.swing.JTextField();
        jQTE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDESC = new javax.swing.JTextArea();
        jValider = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jRETURN = new javax.swing.JLabel();
        jIDMOD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDENTRE = new com.toedter.calendar.JDateChooser();
        jDSORTIE = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1111, 107));

        jpAddProd.setBackground(new java.awt.Color(229, 229, 250));
        jpAddProd.setPreferredSize(new java.awt.Dimension(757, 111));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Modifier un Produit");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Nom du produit :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Quantité :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Prix Unitaire :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setText("Date d'entrée :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setText("Date de sortie :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel7.setText("Description :");

        jPU.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jNOMPROD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jNOMPROD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNOMPROD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jQTE.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jQTE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQTE.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jDESC.setColumns(10);
        jDESC.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jDESC.setLineWrap(true);
        jDESC.setRows(5);
        jDESC.setTabSize(9);
        jDESC.setText(" ");
        jDESC.setWrapStyleWord(true);
        jDESC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jDESC);

        jValider.setBackground(new java.awt.Color(255, 255, 255));
        jValider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jValider.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\save3.png")); // NOI18N
        jValider.setText("Enregistrer");
        jValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderActionPerformed(evt);
            }
        });

        jReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\rese1.png")); // NOI18N
        jReset.setText("Réinitialiser");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jRETURN.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jRETURN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRETURNMouseClicked(evt);
            }
        });

        jIDMOD.setBackground(new java.awt.Color(255, 102, 102));
        jIDMOD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jIDMOD.setForeground(new java.awt.Color(255, 255, 255));
        jIDMOD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jIDMOD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("ID du produit à modifier:");

        jDENTRE.setDateFormatString("yyyy-MM-dd");
        jDENTRE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jDSORTIE.setDateFormatString("yyyy-MM-dd");
        jDSORTIE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpAddProdLayout = new javax.swing.GroupLayout(jpAddProd);
        jpAddProd.setLayout(jpAddProdLayout);
        jpAddProdLayout.setHorizontalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRETURN)
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDENTRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPU, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jQTE, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jNOMPROD, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jIDMOD, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jDSORTIE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jpAddProdLayout.setVerticalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIDMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNOMPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPU, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQTE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAddProdLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpAddProdLayout.createSequentialGroup()
                                .addComponent(jDENTRE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDSORTIE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addComponent(jRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jValider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderActionPerformed

        
        String nomProd = jNOMPROD.getText();
        
        Double PU = Double.parseDouble(jPU.getText());
        
        int quantiteProd = Integer.parseInt(jQTE.getText());
        
         SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        
         String dateentre = d.format(jDENTRE.getDate());
        
        String dateexp = d.format(jDSORTIE.getDate());
        
        String Description = jDESC.getText();
        
        Date dateEntre = Date.valueOf(dateentre);
        
        Date dateExp = Date.valueOf(dateexp);
        
        int id=Integer.parseInt(jIDMOD.getText()) ;
 
        Produit c = new Produit(id, nomProd, PU, quantiteProd, dateEntre, dateExp, Description);
        
        boolean res=Produit.UpdateProduit(c,id);
        JOptionPane jp=new JOptionPane();

            if(res==true){
                JOptionPane.showMessageDialog(this, "Produit modifié avec succès", "Bravo", JOptionPane.INFORMATION_MESSAGE);
                 this.setVisible(false);
                System.out.println("done");

            }else{

            jp.showMessageDialog(this,"Erreur Veuillez saisir les informations","Erreur",JOptionPane.ERROR_MESSAGE);
        }

        
                                      
    }//GEN-LAST:event_jValiderActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
       
        jIDMOD.setText("");
        jNOMPROD.setText("");
        jPU.setText("");
        jQTE.setText("");
        jDENTRE.setDate(null);
        jDSORTIE.setDate(null);
        jDESC.setText("");
    }//GEN-LAST:event_jResetActionPerformed

    private void jRETURNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRETURNMouseClicked
        this.setVisible(false);
        
        new interfaceProduit().setVisible(true);
    }//GEN-LAST:event_jRETURNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDENTRE;
    private javax.swing.JTextArea jDESC;
    private com.toedter.calendar.JDateChooser jDSORTIE;
    private javax.swing.JTextField jIDMOD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNOMPROD;
    private javax.swing.JTextField jPU;
    private javax.swing.JTextField jQTE;
    private javax.swing.JLabel jRETURN;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jValider;
    private javax.swing.JPanel jpAddProd;
    // End of variables declaration//GEN-END:variables
}
