/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI_Produit;

import GUI_Fournisseur.*;
import GUI_Produit.*;
import GUI.*;
import static GUI_Produit.VisualiserEtatProd.jtable;
import Singleton.SingletonConnection;
import entity.Fournisseur;
import entity.Helper;
import entity.Produit;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.Vector;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Yassine
 */
public class VisualiserEtatProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterProduit
     */
    public VisualiserEtatProd() {
        initComponents();
        this.setSize(791, 680);
        
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAddProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRETURN = new javax.swing.JLabel();
        jFILTRERPROD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSupprimer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1111, 107));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jpAddProd.setBackground(new java.awt.Color(229, 229, 250));
        jpAddProd.setPreferredSize(new java.awt.Dimension(757, 111));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Visualiser ou supprimer un produit");

        jRETURN.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jRETURN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRETURNMouseClicked(evt);
            }
        });

        jFILTRERPROD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jFILTRERPROD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFILTRERPROD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jFILTRERPROD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFILTRERPROD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFILTRERPRODKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Chercher un produit : ");

        jSupprimer.setBackground(new java.awt.Color(255, 255, 255));
        jSupprimer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSupprimer.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\del1.png")); // NOI18N
        jSupprimer.setText("Supprimer");
        jSupprimer.setToolTipText("");
        jSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimerActionPerformed(evt);
            }
        });

        jtable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom du produit", "Prix Unitaire", "Quantité", "Date d'entrée", "Date de sortie", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable.setGridColor(new java.awt.Color(255, 102, 102));
        jtable.setMinimumSize(new java.awt.Dimension(200, 0));
        jtable.setSelectionBackground(new java.awt.Color(255, 153, 102));
        jtable.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jtable);

        jLabel3.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("Information : Vous pouvez retirer un produit par la séléction d'une ligne du tablau ensuite cliquez sur \"Supprimer\" .");

        javax.swing.GroupLayout jpAddProdLayout = new javax.swing.GroupLayout(jpAddProd);
        jpAddProd.setLayout(jpAddProdLayout);
        jpAddProdLayout.setHorizontalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRETURN)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(jFILTRERPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddProdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAddProdLayout.setVerticalGroup(
            jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jpAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFILTRERPROD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRETURNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRETURNMouseClicked
        this.setVisible(false);
         new interfaceProduit().setVisible(true);
    }//GEN-LAST:event_jRETURNMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      String req = "SELECT * from produit";
       try{
           // execution de la requete 
           Connection conn = SingletonConnection.getConnection();
           Statement stmt = conn.createStatement();
           ResultSet rs = stmt.executeQuery(req);
           // creation du model de la jtable
           DefaultTableModel jtbalModel1 = Helper.buildTableModel(rs);
           jtable.setModel(jtbalModel1);}
       catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jFILTRERPRODKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFILTRERPRODKeyReleased
        String nomprod=jFILTRERPROD.getText();
      
        DefaultTableModel model = (DefaultTableModel)jtable.getModel();
        TableRowSorter trs = new TableRowSorter(model);
        jtable.setRowSorter(trs);
        
        trs.setRowFilter(RowFilter.regexFilter(nomprod));
    }//GEN-LAST:event_jFILTRERPRODKeyReleased

    private void jSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupprimerActionPerformed
           
        int row = jtable.getSelectedRow();
        int id = (int) jtable.getValueAt(row, 0);
       Produit.DelProd(id);

        String req = "SELECT * from produit";
        try{
            // execution de la requete
            Connection conn = SingletonConnection.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(req);
            // creation du model de la jtable
            DefaultTableModel jtbalModel1 = Helper.buildTableModel(rs);
            jtable.setModel(jtbalModel1);}
        catch(Exception e){
            e.printStackTrace();
        }     
    }//GEN-LAST:event_jSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jFILTRERPROD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jRETURN;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSupprimer;
    private javax.swing.JPanel jpAddProd;
    public static javax.swing.JTable jtable;
    // End of variables declaration//GEN-END:variables
}
