/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import GUI_PDF.GenPDF;
import GUI_Produit.VisualiserEtatProd;
import Singleton.SingletonConnection;
import java.awt.Color;
import java.awt.Image;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.prefs.BackingStoreException;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;



/**
 *
 * @author Yassine
 */
public class AdminGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() throws SQLException, ClassNotFoundException {
        initComponents();
       this.setSize(1015,650);
      
       this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        jGRAPH1.add(createDemoPie());
        jBARGRAPH.add(createDemoBar());
        
    }
     
    public static JFreeChart showPieChart(){
        DefaultPieDataset dataset = new DefaultPieDataset();
        Connection cnx = SingletonConnection.getConnection();
        String sql = "Select nomProd,quantiteProd FROM produit";
        try {
            Statement st = cnx.createStatement();
            ResultSet r = st.executeQuery(sql);
            while(r.next()){
                 dataset.setValue( 
         r.getString( "nomProd" ) ,
         Integer.parseInt( r.getString( "quantiteProd" )));
            }
              
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        JFreeChart chart = ChartFactory.createPieChart( "Etat du stock", dataset, true, true,false );          
         ChartPanel pieChartPanel = new ChartPanel(chart);
         pieChartPanel.setSize(320, 247);
         jGRAPH1.add(pieChartPanel);
         jGRAPH1.validate();
               
        return chart;
        
    }
     public static JPanel createDemoPie() throws SQLException, ClassNotFoundException {
      JFreeChart chart;  
        chart = showPieChart();
      return new ChartPanel( chart ); 
   }
   
     
    public static JFreeChart showBarChart(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
        Connection cnx = SingletonConnection.getConnection();
        String sql = "SELECT nomProd,quantiteProd,dateEntre FROM `produit` ORDER BY `quantiteProd` ASC ";
        try {
            Statement st = cnx.createStatement();
            ResultSet r = st.executeQuery(sql);
            while(r.next()){
                 
                String nomProd = r.getString("nomProd" ) ;
                int qte = r.getInt( "quantiteProd" );
                Date dateEntre = r.getDate("dateEntre");
                dataset.setValue(qte, nomProd,dateEntre);

            }
       
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
         JFreeChart chart = ChartFactory.createBarChart("Evolution du stock", "nomProd", "qteProd",dataset, PlotOrientation.VERTICAL, true, true, false);         
         CategoryPlot p = chart.getCategoryPlot();
         ChartPanel BarChartPanel = new ChartPanel(chart);
         
         BarChartPanel.setSize(745, 253);
         chart.getPlot().setBackgroundPaint( new Color(255, 255, 255));
         jBARGRAPH.add(BarChartPanel);
         jBARGRAPH.validate();
               
        return chart;
    } 
      public static JPanel createDemoBar() throws SQLException, ClassNotFoundException {
      JFreeChart chart;  
        chart = showBarChart();
      return new ChartPanel( chart ); 
   }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAdmin = new javax.swing.JDesktopPane();
        bg = new javax.swing.JPanel();
        JPLEFTadmin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jProduit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFournisseur = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jClient = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jHisto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        deconnexion1 = new javax.swing.JLabel();
        jPDF = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JPRIGHTadmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jGRAPH1 = new javax.swing.JPanel();
        jBARGRAPH = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jdpAdmin.setPreferredSize(new java.awt.Dimension(100, 100));

        bg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bg.setDoubleBuffered(false);

        JPLEFTadmin.setBackground(new java.awt.Color(0, 204, 204));
        JPLEFTadmin.setPreferredSize(new java.awt.Dimension(227, 680));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu Principal");

        jProduit.setBackground(new java.awt.Color(0, 204, 204));
        jProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProduitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProduitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jProduitMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Produit");

        javax.swing.GroupLayout jProduitLayout = new javax.swing.GroupLayout(jProduit);
        jProduit.setLayout(jProduitLayout);
        jProduitLayout.setHorizontalGroup(
            jProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProduitLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jProduitLayout.setVerticalGroup(
            jProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProduitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFournisseur.setBackground(new java.awt.Color(0, 204, 204));
        jFournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFournisseurMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFournisseurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFournisseurMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Fournisseur");

        javax.swing.GroupLayout jFournisseurLayout = new javax.swing.GroupLayout(jFournisseur);
        jFournisseur.setLayout(jFournisseurLayout);
        jFournisseurLayout.setHorizontalGroup(
            jFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFournisseurLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFournisseurLayout.setVerticalGroup(
            jFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFournisseurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jClient.setBackground(new java.awt.Color(0, 204, 204));
        jClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jClientMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Client");

        javax.swing.GroupLayout jClientLayout = new javax.swing.GroupLayout(jClient);
        jClient.setLayout(jClientLayout);
        jClientLayout.setHorizontalGroup(
            jClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jClientLayout.setVerticalGroup(
            jClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jHisto.setBackground(new java.awt.Color(0, 204, 204));
        jHisto.setPreferredSize(new java.awt.Dimension(160, 61));
        jHisto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHistoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jHistoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jHistoMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("<html><center><p>Visualiser l'historique <br/>des commandes</p</center></html>");

        javax.swing.GroupLayout jHistoLayout = new javax.swing.GroupLayout(jHisto);
        jHisto.setLayout(jHistoLayout);
        jHistoLayout.setHorizontalGroup(
            jHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHistoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jHistoLayout.setVerticalGroup(
            jHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHistoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        deconnexion1.setBackground(new java.awt.Color(255, 255, 255));
        deconnexion1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        deconnexion1.setForeground(new java.awt.Color(255, 255, 255));
        deconnexion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deconnexion1.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\logout1.png")); // NOI18N
        deconnexion1.setText("Déconnexion");
        deconnexion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexion1MouseClicked(evt);
            }
        });

        jPDF.setBackground(new java.awt.Color(0, 204, 204));
        jPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPDFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPDFMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Rapport PDF");

        javax.swing.GroupLayout jPDFLayout = new javax.swing.GroupLayout(jPDF);
        jPDF.setLayout(jPDFLayout);
        jPDFLayout.setHorizontalGroup(
            jPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDFLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPDFLayout.setVerticalGroup(
            jPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPLEFTadminLayout = new javax.swing.GroupLayout(JPLEFTadmin);
        JPLEFTadmin.setLayout(JPLEFTadminLayout);
        JPLEFTadminLayout.setHorizontalGroup(
            JPLEFTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHisto, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
            .addComponent(jProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jFournisseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPLEFTadminLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPLEFTadminLayout.createSequentialGroup()
                .addComponent(jPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPLEFTadminLayout.createSequentialGroup()
                .addComponent(deconnexion1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPLEFTadminLayout.setVerticalGroup(
            JPLEFTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTadminLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHisto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(deconnexion1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        JPRIGHTadmin.setBackground(new java.awt.Color(235, 235, 253));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Dashboard");

        jGRAPH1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jGRAPH1Layout = new javax.swing.GroupLayout(jGRAPH1);
        jGRAPH1.setLayout(jGRAPH1Layout);
        jGRAPH1Layout.setHorizontalGroup(
            jGRAPH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jGRAPH1Layout.setVerticalGroup(
            jGRAPH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        jBARGRAPH.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jBARGRAPHLayout = new javax.swing.GroupLayout(jBARGRAPH);
        jBARGRAPH.setLayout(jBARGRAPHLayout);
        jBARGRAPHLayout.setHorizontalGroup(
            jBARGRAPHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jBARGRAPHLayout.setVerticalGroup(
            jBARGRAPHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPRIGHTadminLayout = new javax.swing.GroupLayout(JPRIGHTadmin);
        JPRIGHTadmin.setLayout(JPRIGHTadminLayout);
        JPRIGHTadminLayout.setHorizontalGroup(
            JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                .addGroup(JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1))
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBARGRAPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jGRAPH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        JPRIGHTadminLayout.setVerticalGroup(
            JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGRAPH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBARGRAPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(JPLEFTadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JPRIGHTadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPLEFTadmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );

        jdpAdmin.setLayer(bg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpAdminLayout = new javax.swing.GroupLayout(jdpAdmin);
        jdpAdmin.setLayout(jdpAdminLayout);
        jdpAdminLayout.setHorizontalGroup(
            jdpAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1532, Short.MAX_VALUE)
            .addGroup(jdpAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdpAdminLayout.setVerticalGroup(
            jdpAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
            .addGroup(jdpAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProduitMouseClicked
            jProduit.setBackground(new Color(0,153,153));
            jdpAdmin.add(new interfaceProduit()).setVisible(true);
    }//GEN-LAST:event_jProduitMouseClicked

    private void jFournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFournisseurMouseClicked
   jFournisseur.setBackground(new Color(0,153,153));  
    jdpAdmin.add(new interfaceFournisseur()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jFournisseurMouseClicked

    private void jProduitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProduitMouseExited
        jProduit.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jProduitMouseExited

    private void jFournisseurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFournisseurMouseExited
    jFournisseur.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jFournisseurMouseExited

    private void jProduitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProduitMouseEntered
    
        jProduit.setBackground(new Color(0,204,153)); 
    }//GEN-LAST:event_jProduitMouseEntered

    private void jFournisseurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFournisseurMouseEntered
        jFournisseur.setBackground(new Color(0,204,153)); 
    }//GEN-LAST:event_jFournisseurMouseEntered

    private void jClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientMouseEntered
jClient.setBackground(new Color(0,204,153));         // TODO add your handling code here:
    }//GEN-LAST:event_jClientMouseEntered

    private void jClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientMouseExited
        // TODO add your handling code here:
        jClient.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jClientMouseExited

    private void jHistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHistoMouseClicked
        jdpAdmin.add(new interfaceGestionCommande()).setVisible(true);
    }//GEN-LAST:event_jHistoMouseClicked

    private void jHistoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHistoMouseEntered
        jHisto.setBackground(new Color(0,204,153)); 
    }//GEN-LAST:event_jHistoMouseEntered

    private void jHistoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHistoMouseExited
        jHisto.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jHistoMouseExited

    private void jClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientMouseClicked
        jdpAdmin.add(new interfaceGestionClient()).setVisible(true);
    }//GEN-LAST:event_jClientMouseClicked

    private void deconnexion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexion1MouseClicked
        this.setVisible(false);
        new MainGUI().setVisible(true);
    }//GEN-LAST:event_deconnexion1MouseClicked

    private void jPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDFMouseClicked
        jPDF.setBackground(new Color(0,153,153));
        jdpAdmin.add(new GenPDF()).setVisible(true);
    }//GEN-LAST:event_jPDFMouseClicked

    private void jPDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDFMouseEntered
        jPDF.setBackground(new Color(0,204,153)); 
    }//GEN-LAST:event_jPDFMouseEntered

    private void jPDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDFMouseExited
        jPDF.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jPDFMouseExited

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
   
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLEFTadmin;
    private javax.swing.JPanel JPRIGHTadmin;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel deconnexion1;
    public static javax.swing.JPanel jBARGRAPH;
    private javax.swing.JPanel jClient;
    private javax.swing.JPanel jFournisseur;
    public static javax.swing.JPanel jGRAPH1;
    private javax.swing.JPanel jHisto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPDF;
    private javax.swing.JPanel jProduit;
    private javax.swing.JDesktopPane jdpAdmin;
    // End of variables declaration//GEN-END:variables
}
