/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import GUI_Produit.AjouterProduit;
import GUI_Produit.ModifierProduit;

import GUI_Produit.VisualiserEtatProd;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class interfaceProduit extends javax.swing.JInternalFrame {

    /**
     * Creates new form interfaceProduit
     */
    
    Color setColor,resetColor;
    public interfaceProduit() {
        initComponents();
        this.setSize(1015,650);
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);      
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpProd = new javax.swing.JDesktopPane();
        JPRIGHTproduit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jreturn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPLEFTproduit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jAddProd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEditProd = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jEtatProd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 745));

        JPRIGHTproduit.setBackground(new java.awt.Color(229, 229, 250));
        JPRIGHTproduit.setPreferredSize(new java.awt.Dimension(791, 680));
        JPRIGHTproduit.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Gestion des Produits");

        jreturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jreturnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\gestProd1.jpg")); // NOI18N

        javax.swing.GroupLayout JPRIGHTproduitLayout = new javax.swing.GroupLayout(JPRIGHTproduit);
        JPRIGHTproduit.setLayout(JPRIGHTproduitLayout);
        JPRIGHTproduitLayout.setHorizontalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPRIGHTproduitLayout.setVerticalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addGroup(JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        jdpProd.setLayer(JPRIGHTproduit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpProdLayout = new javax.swing.GroupLayout(jdpProd);
        jdpProd.setLayout(jdpProdLayout);
        jdpProdLayout.setHorizontalGroup(
            jdpProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        jdpProdLayout.setVerticalGroup(
            jdpProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        JPLEFTproduit.setBackground(new java.awt.Color(0, 204, 204));
        JPLEFTproduit.setPreferredSize(new java.awt.Dimension(227, 680));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu Produit");

        jAddProd.setBackground(new java.awt.Color(0, 204, 204));
        jAddProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAddProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAddProdMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ajouter un produit");

        javax.swing.GroupLayout jAddProdLayout = new javax.swing.GroupLayout(jAddProd);
        jAddProd.setLayout(jAddProdLayout);
        jAddProdLayout.setHorizontalGroup(
            jAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddProdLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jAddProdLayout.setVerticalGroup(
            jAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAddProdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jEditProd.setBackground(new java.awt.Color(0, 204, 204));
        jEditProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEditProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEditProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jEditProdMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("<html><center><p>Modifier les informations<br/>d'un produit</p</center></html>");

        javax.swing.GroupLayout jEditProdLayout = new javax.swing.GroupLayout(jEditProd);
        jEditProd.setLayout(jEditProdLayout);
        jEditProdLayout.setHorizontalGroup(
            jEditProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditProdLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jEditProdLayout.setVerticalGroup(
            jEditProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jEtatProd.setBackground(new java.awt.Color(0, 204, 204));
        jEtatProd.setPreferredSize(new java.awt.Dimension(160, 61));
        jEtatProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtatProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEtatProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jEtatProdMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("<html><center><p>Supprimer ou visualiser <br/>l'état des produits</p></center></html>");

        javax.swing.GroupLayout jEtatProdLayout = new javax.swing.GroupLayout(jEtatProd);
        jEtatProd.setLayout(jEtatProdLayout);
        jEtatProdLayout.setHorizontalGroup(
            jEtatProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEtatProdLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jEtatProdLayout.setVerticalGroup(
            jEtatProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPLEFTproduitLayout = new javax.swing.GroupLayout(JPLEFTproduit);
        JPLEFTproduit.setLayout(JPLEFTproduitLayout);
        JPLEFTproduitLayout.setHorizontalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEtatProd, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGroup(JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEditProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPLEFTproduitLayout.setVerticalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEditProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEtatProd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLEFTproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdpProd))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpProd)
            .addComponent(JPLEFTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddProdMouseClicked
            jdpProd.add(new AjouterProduit()).setVisible(true);
    }//GEN-LAST:event_jAddProdMouseClicked

    private void jAddProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddProdMouseExited
        jAddProd.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jAddProdMouseExited

    private void jEditProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditProdMouseClicked
       
        jdpProd.add(new ModifierProduit()).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jEditProdMouseClicked

    private void jEditProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditProdMouseExited
        jEditProd.setBackground(new Color(0,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditProdMouseExited

    private void jEtatProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtatProdMouseClicked
    jdpProd.add(new VisualiserEtatProd()).setVisible(true);// TODO add your handling code here:        
        
    }//GEN-LAST:event_jEtatProdMouseClicked

    private void jEtatProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtatProdMouseExited
     jEtatProd.setBackground(new Color(0,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_jEtatProdMouseExited

    private void jreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jreturnMouseClicked
        this.setVisible(false);
        try {
            new AdminGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(interfaceProduit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaceProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jreturnMouseClicked

    private void jAddProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddProdMouseEntered
        
         jAddProd.setBackground(new Color(0,204,153)); 
        
    }//GEN-LAST:event_jAddProdMouseEntered

    private void jEditProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditProdMouseEntered
     jEditProd.setBackground(new Color(0,204,153));         // TODO add your handling code here:
    }//GEN-LAST:event_jEditProdMouseEntered

    private void jEtatProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtatProdMouseEntered
    jEtatProd.setBackground(new Color(0,204,153));         // TODO add your handling code here:
    }//GEN-LAST:event_jEtatProdMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLEFTproduit;
    private javax.swing.JPanel JPRIGHTproduit;
    private javax.swing.JPanel jAddProd;
    private javax.swing.JPanel jEditProd;
    private javax.swing.JPanel jEtatProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDesktopPane jdpProd;
    private javax.swing.JLabel jreturn;
    // End of variables declaration//GEN-END:variables
}
