/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import GUI_GestionClient.ListerClients;
import java.util.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class interfaceGestionClient extends javax.swing.JInternalFrame {

    /**
     * Creates new form interfaceProduit
     */
    
    Color setColor,resetColor;
    public interfaceGestionClient() {
        initComponents();
        this.setSize(1015,650);
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);      
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpGestClient = new javax.swing.JDesktopPane();
        JPRIGHTproduit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jreturn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPLEFTclient = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jAddProd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 745));

        JPRIGHTproduit.setBackground(new java.awt.Color(229, 229, 250));
        JPRIGHTproduit.setPreferredSize(new java.awt.Dimension(791, 680));
        JPRIGHTproduit.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Gestion des Clients");

        jreturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jreturnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\gestclient.png")); // NOI18N

        javax.swing.GroupLayout JPRIGHTproduitLayout = new javax.swing.GroupLayout(JPRIGHTproduit);
        JPRIGHTproduit.setLayout(JPRIGHTproduitLayout);
        JPRIGHTproduitLayout.setHorizontalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        JPRIGHTproduitLayout.setVerticalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addGroup(JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        jdpGestClient.setLayer(JPRIGHTproduit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpGestClientLayout = new javax.swing.GroupLayout(jdpGestClient);
        jdpGestClient.setLayout(jdpGestClientLayout);
        jdpGestClientLayout.setHorizontalGroup(
            jdpGestClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        jdpGestClientLayout.setVerticalGroup(
            jdpGestClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        JPLEFTclient.setBackground(new java.awt.Color(0, 204, 204));
        JPLEFTclient.setPreferredSize(new java.awt.Dimension(227, 680));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu Client");

        jAddProd.setBackground(new java.awt.Color(0, 204, 204));
        jAddProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAddProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAddProdMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Lister ou supprimer clients");

        javax.swing.GroupLayout jAddProdLayout = new javax.swing.GroupLayout(jAddProd);
        jAddProd.setLayout(jAddProdLayout);
        jAddProdLayout.setHorizontalGroup(
            jAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAddProdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(57, 57, 57))
        );
        jAddProdLayout.setVerticalGroup(
            jAddProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAddProdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPLEFTclientLayout = new javax.swing.GroupLayout(JPLEFTclient);
        JPLEFTclient.setLayout(JPLEFTclientLayout);
        JPLEFTclientLayout.setHorizontalGroup(
            JPLEFTclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTclientLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPLEFTclientLayout.createSequentialGroup()
                .addComponent(jAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPLEFTclientLayout.setVerticalGroup(
            JPLEFTclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTclientLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLEFTclient, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdpGestClient))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpGestClient)
            .addComponent(JPLEFTclient, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddProdMouseClicked
            jdpGestClient.add(new ListerClients()).setVisible(true);
        
    }//GEN-LAST:event_jAddProdMouseClicked

    private void jAddProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddProdMouseExited
        jAddProd.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jAddProdMouseExited

    private void jreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jreturnMouseClicked
        this.setVisible(false);
        try {
            new AdminGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(interfaceGestionClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaceGestionClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jreturnMouseClicked

    private void jAddProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddProdMouseEntered
        
         jAddProd.setBackground(new Color(0,204,153)); 
        
    }//GEN-LAST:event_jAddProdMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLEFTclient;
    private javax.swing.JPanel JPRIGHTproduit;
    private javax.swing.JPanel jAddProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JDesktopPane jdpGestClient;
    private javax.swing.JLabel jreturn;
    // End of variables declaration//GEN-END:variables
}
