/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import GUI_Fournisseur.AjouterFournisseur;
import GUI_Fournisseur.ModifierFournisseur;
import GUI_Fournisseur.VisualiserFournisseur;
import GUI_Produit.ModifierProduit;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class interfaceFournisseur extends javax.swing.JInternalFrame {

    /**
     * Creates new form interfaceProduit
     */
    public interfaceFournisseur() {
        initComponents();
        this.setSize(1015,650);
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpFourn = new javax.swing.JDesktopPane();
        JPRIGHTproduit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jreturn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPLEFTproduit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jAddFourn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEditFourn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jVisualiserFourn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 745));

        JPRIGHTproduit.setBackground(new java.awt.Color(229, 229, 250));
        JPRIGHTproduit.setPreferredSize(new java.awt.Dimension(791, 680));
        JPRIGHTproduit.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Gestion des Fournisseurs");

        jreturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jreturnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\supplier1.png")); // NOI18N

        javax.swing.GroupLayout JPRIGHTproduitLayout = new javax.swing.GroupLayout(JPRIGHTproduit);
        JPRIGHTproduit.setLayout(JPRIGHTproduitLayout);
        JPRIGHTproduitLayout.setHorizontalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        JPRIGHTproduitLayout.setVerticalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addGroup(JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jdpFourn.setLayer(JPRIGHTproduit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpFournLayout = new javax.swing.GroupLayout(jdpFourn);
        jdpFourn.setLayout(jdpFournLayout);
        jdpFournLayout.setHorizontalGroup(
            jdpFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        jdpFournLayout.setVerticalGroup(
            jdpFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        JPLEFTproduit.setBackground(new java.awt.Color(0, 204, 204));
        JPLEFTproduit.setPreferredSize(new java.awt.Dimension(227, 680));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu Fournisseur");

        jAddFourn.setBackground(new java.awt.Color(0, 204, 204));
        jAddFourn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddFournMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAddFournMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAddFournMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ajouter un Fournisseur");

        javax.swing.GroupLayout jAddFournLayout = new javax.swing.GroupLayout(jAddFourn);
        jAddFourn.setLayout(jAddFournLayout);
        jAddFournLayout.setHorizontalGroup(
            jAddFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddFournLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jAddFournLayout.setVerticalGroup(
            jAddFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddFournLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jEditFourn.setBackground(new java.awt.Color(0, 204, 204));
        jEditFourn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEditFournMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEditFournMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jEditFournMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("<html><center><p>Modifier les informations<br/>d'un Fournisseur</p</center></html>");

        javax.swing.GroupLayout jEditFournLayout = new javax.swing.GroupLayout(jEditFourn);
        jEditFourn.setLayout(jEditFournLayout);
        jEditFournLayout.setHorizontalGroup(
            jEditFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditFournLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jEditFournLayout.setVerticalGroup(
            jEditFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jVisualiserFourn.setBackground(new java.awt.Color(0, 204, 204));
        jVisualiserFourn.setPreferredSize(new java.awt.Dimension(160, 61));
        jVisualiserFourn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVisualiserFournMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jVisualiserFournMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jVisualiserFournMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("<html><center><p>Visualiser ou supprimer</p> un fournisseurs</center></html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jVisualiserFournLayout = new javax.swing.GroupLayout(jVisualiserFourn);
        jVisualiserFourn.setLayout(jVisualiserFournLayout);
        jVisualiserFournLayout.setHorizontalGroup(
            jVisualiserFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jVisualiserFournLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jVisualiserFournLayout.setVerticalGroup(
            jVisualiserFournLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jVisualiserFournLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPLEFTproduitLayout = new javax.swing.GroupLayout(JPLEFTproduit);
        JPLEFTproduit.setLayout(JPLEFTproduitLayout);
        JPLEFTproduitLayout.setHorizontalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGroup(JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditFourn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVisualiserFourn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddFourn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPLEFTproduitLayout.setVerticalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jAddFourn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEditFourn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVisualiserFourn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLEFTproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdpFourn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpFourn)
            .addComponent(JPLEFTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddFournMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddFournMouseClicked
        jAddFourn.setBackground(new Color(0,153,153)); 
        jdpFourn.add(new AjouterFournisseur()).setVisible(true);
    }//GEN-LAST:event_jAddFournMouseClicked

    private void jAddFournMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddFournMouseExited
        jAddFourn.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jAddFournMouseExited

    private void jEditFournMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditFournMouseClicked
jEditFourn.setBackground(new Color(0,153,153));      
        jdpFourn.add(new ModifierFournisseur()).setVisible(true);
    }//GEN-LAST:event_jEditFournMouseClicked

    private void jEditFournMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditFournMouseExited
  jEditFourn.setBackground(new Color(0,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditFournMouseExited

    private void jVisualiserFournMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisualiserFournMouseClicked
jVisualiserFourn.setBackground(new Color(0,153,153));        
        jdpFourn.add(new VisualiserFournisseur()).setVisible(true);
    }//GEN-LAST:event_jVisualiserFournMouseClicked

    private void jVisualiserFournMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisualiserFournMouseExited
        // TODO add your handling code here:
        jVisualiserFourn.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jVisualiserFournMouseExited

    private void jreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jreturnMouseClicked
        this.setVisible(false);
        try {
            new AdminGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(interfaceFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaceFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jreturnMouseClicked

    private void jAddFournMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddFournMouseEntered
        jAddFourn.setBackground(new Color(0,204,153)); 
    }//GEN-LAST:event_jAddFournMouseEntered

    private void jEditFournMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditFournMouseEntered
        // TODO add your handling code here:
        jEditFourn.setBackground(new Color(0,204,153));
    }//GEN-LAST:event_jEditFournMouseEntered

    private void jVisualiserFournMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisualiserFournMouseEntered
        // TODO add your handling code here:
        jVisualiserFourn.setBackground(new Color(0,204,153));
    }//GEN-LAST:event_jVisualiserFournMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLEFTproduit;
    private javax.swing.JPanel JPRIGHTproduit;
    private javax.swing.JPanel jAddFourn;
    private javax.swing.JPanel jEditFourn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jVisualiserFourn;
    private javax.swing.JDesktopPane jdpFourn;
    private javax.swing.JLabel jreturn;
    // End of variables declaration//GEN-END:variables
}
