/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import GUI.*;
import GUI_Commande_Admin.adminVisualiserCommande;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Yassine
 */
public class interfaceGestionCommande extends javax.swing.JInternalFrame {

    /**
     * Creates new form interfaceProduit
     */
    
    Color setColor,resetColor;
    public interfaceGestionCommande() {
        initComponents();
        this.setSize(1015,650);
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);      
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpProd = new javax.swing.JDesktopPane();
        JPRIGHTproduit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jreturn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPLEFTproduit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jVisHistoComm = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 745));

        JPRIGHTproduit.setBackground(new java.awt.Color(229, 229, 250));
        JPRIGHTproduit.setPreferredSize(new java.awt.Dimension(791, 680));
        JPRIGHTproduit.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Gestion des commandes");

        jreturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jreturnMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\order1.png")); // NOI18N

        javax.swing.GroupLayout JPRIGHTproduitLayout = new javax.swing.GroupLayout(JPRIGHTproduit);
        JPRIGHTproduit.setLayout(JPRIGHTproduitLayout);
        JPRIGHTproduitLayout.setHorizontalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRIGHTproduitLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        JPRIGHTproduitLayout.setVerticalGroup(
            JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                .addGroup(JPRIGHTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPRIGHTproduitLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpProd.setLayer(JPRIGHTproduit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpProdLayout = new javax.swing.GroupLayout(jdpProd);
        jdpProd.setLayout(jdpProdLayout);
        jdpProdLayout.setHorizontalGroup(
            jdpProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        jdpProdLayout.setVerticalGroup(
            jdpProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        JPLEFTproduit.setBackground(new java.awt.Color(0, 204, 204));
        JPLEFTproduit.setPreferredSize(new java.awt.Dimension(227, 680));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu commande");

        jVisHistoComm.setBackground(new java.awt.Color(0, 204, 204));
        jVisHistoComm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVisHistoCommMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jVisHistoCommMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jVisHistoCommMouseExited(evt);
            }
        });

        jlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlabel.setText("<html><center><p>Visualiser l'état</p>des commandes</center></html>");

        javax.swing.GroupLayout jVisHistoCommLayout = new javax.swing.GroupLayout(jVisHistoComm);
        jVisHistoComm.setLayout(jVisHistoCommLayout);
        jVisHistoCommLayout.setHorizontalGroup(
            jVisHistoCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jVisHistoCommLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jVisHistoCommLayout.setVerticalGroup(
            jVisHistoCommLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPLEFTproduitLayout = new javax.swing.GroupLayout(JPLEFTproduit);
        JPLEFTproduit.setLayout(JPLEFTproduitLayout);
        JPLEFTproduitLayout.setHorizontalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jVisHistoComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPLEFTproduitLayout.setVerticalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jVisHistoComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLEFTproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdpProd))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpProd)
            .addComponent(JPLEFTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVisHistoCommMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisHistoCommMouseClicked
        jVisHistoComm.setBackground(new Color(0,153,153));       
        jdpProd.add(new adminVisualiserCommande()).setVisible(true);
        
    }//GEN-LAST:event_jVisHistoCommMouseClicked

    private void jVisHistoCommMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisHistoCommMouseExited
        jVisHistoComm.setBackground(new Color(0,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_jVisHistoCommMouseExited

    private void jreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jreturnMouseClicked
        this.setVisible(false);
        try {
            new AdminGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(interfaceGestionCommande.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaceGestionCommande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jreturnMouseClicked

    private void jVisHistoCommMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisHistoCommMouseEntered
     jVisHistoComm.setBackground(new Color(0,204,153));         // TODO add your handling code here:
    }//GEN-LAST:event_jVisHistoCommMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLEFTproduit;
    private javax.swing.JPanel JPRIGHTproduit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jVisHistoComm;
    private javax.swing.JDesktopPane jdpProd;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jreturn;
    // End of variables declaration//GEN-END:variables
}
