/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import entity.Admin;
import entity.Client;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author Yassine
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setSize(1015,650);
        this.setResizable(false);
        getContentPane().setBackground(Color.white);
        JPRIGHT.setBackground(Color.white);
        scaleImage1();
        ImageIcon iconjf = new ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\frameIcon1.png");
        setIconImage(iconjf.getImage());

    }  

    int xMouse,yMouse;

     public void scaleImage1(){
        ImageIcon icon = new ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\1.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(JLIMAGE.getWidth(), JLIMAGE.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        JLIMAGE.setIcon(scaledIcon);   
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDPmain = new javax.swing.JDesktopPane();
        bg = new javax.swing.JPanel();
        JPRIGHT = new javax.swing.JPanel();
        JLIMAGE = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPLEFT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jConnexion = new javax.swing.JButton();
        jlinscription = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jheader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jclose = new javax.swing.JLabel();
        jMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Store");
        setUndecorated(true);

        JDPmain.setPreferredSize(new java.awt.Dimension(1000, 745));

        JPRIGHT.setBackground(new java.awt.Color(255, 255, 255));

        JLIMAGE.setText("img");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ⓒ Copyright 2022 | All Rights Reserved");

        javax.swing.GroupLayout JPRIGHTLayout = new javax.swing.GroupLayout(JPRIGHT);
        JPRIGHT.setLayout(JPRIGHTLayout);
        JPRIGHTLayout.setHorizontalGroup(
            JPRIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(JLIMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(JPRIGHTLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPRIGHTLayout.setVerticalGroup(
            JPRIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JLIMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        JPLEFT.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenue");

        jtfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Login");

        jLabel4.setText("Password");

        jConnexion.setBackground(new java.awt.Color(204, 255, 255));
        jConnexion.setText("Se connecter");
        jConnexion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnexionActionPerformed(evt);
            }
        });

        jlinscription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlinscription.setText("Inscription");
        jlinscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlinscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlinscriptionMouseClicked(evt);
            }
        });

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPLEFTLayout = new javax.swing.GroupLayout(JPLEFT);
        JPLEFT.setLayout(JPLEFTLayout);
        JPLEFTLayout.setHorizontalGroup(
            JPLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTLayout.createSequentialGroup()
                .addGroup(JPLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLEFTLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPLEFTLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(JPLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jPassword)))
                    .addGroup(JPLEFTLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPLEFTLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jlinscription, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        JPLEFTLayout.setVerticalGroup(
            JPLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addComponent(jConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jlinscription)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(JPLEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPRIGHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPLEFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPRIGHT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JDPmain.setLayer(bg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDPmainLayout = new javax.swing.GroupLayout(JDPmain);
        JDPmain.setLayout(JDPmainLayout);
        JDPmainLayout.setHorizontalGroup(
            JDPmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(JDPmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JDPmainLayout.createSequentialGroup()
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JDPmainLayout.setVerticalGroup(
            JDPmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(JDPmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JDPmainLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jheader.setBackground(new java.awt.Color(0, 153, 204));
        jheader.setForeground(new java.awt.Color(255, 255, 255));
        jheader.setPreferredSize(new java.awt.Dimension(1142, 100));
        jheader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jheaderMouseDragged(evt);
            }
        });
        jheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jheaderMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("STXinwei", 0, 36)); // NOI18N
        jLabel1.setText("Shopping Store");

        jclose.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jclose.setForeground(new java.awt.Color(255, 255, 255));
        jclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jclose.setText("X");
        jclose.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        jclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcloseMouseClicked(evt);
            }
        });

        jMinimize.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMinimize.setText("–");
        jMinimize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        jMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jheaderLayout = new javax.swing.GroupLayout(jheader);
        jheader.setLayout(jheaderLayout);
        jheaderLayout.setHorizontalGroup(
            jheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jheaderLayout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263)
                .addComponent(jMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jclose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jheaderLayout.setVerticalGroup(
            jheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jheaderLayout.createSequentialGroup()
                .addGroup(jheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jclose)
                    .addComponent(jMinimize))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPmain, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jheader, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jheader, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JDPmain, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLoginActionPerformed
public static String login,password;
public static boolean res2;
    private void jConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnexionActionPerformed
        try {
            login = jtfLogin.getText();
            password = jPassword.getText();

            boolean res1 = Admin.Authentification(login,password);
            res2 = Client.AuthentificationClient(login,password);
            if(res1==true){
                
                //this.setVisible(false);
                JDPmain.removeAll();
                JDPmain.add(new AdminGUI()).setVisible(true);
            }
            else if(res2==true){
                System.out.println("user exist");
                JDPmain.add(new interfaceClient()).setVisible(true);
                // this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Administrateur / Client non trouvé!\nVeuillez créer un compte", "Erreur", ERROR_MESSAGE);
                jtfLogin.setText("");
                jPassword.setText("");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            System.err.println("Erreur jconnexion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jConnexionActionPerformed
    private void jlinscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlinscriptionMouseClicked
            // TODO add your handling code here:
            dispose();
            JFrame jinsc= new interfaceCreerClient();
                   jinsc.setVisible(true);
    }//GEN-LAST:event_jlinscriptionMouseClicked

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jcloseMouseClicked

    private void jMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimizeMouseClicked
       // hide();
        JFrame jf = new JFrame();
        this.setState(jf.ICONIFIED);
      
    }//GEN-LAST:event_jMinimizeMouseClicked

    private void jheaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jheaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jheaderMouseDragged

    private void jheaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jheaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jheaderMousePressed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPmain;
    private javax.swing.JLabel JLIMAGE;
    private javax.swing.JPanel JPLEFT;
    private javax.swing.JPanel JPRIGHT;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jConnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jMinimize;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel jclose;
    private javax.swing.JPanel jheader;
    private javax.swing.JLabel jlinscription;
    private javax.swing.JTextField jtfLogin;
    // End of variables declaration//GEN-END:variables
}
