/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI_PDF;
import GUI.*;
import GUI_Client.visualiserHistoCommande;
import GUI.interfaceGestionCommande;
import GUI_Commande_Admin.adminVisualiserCommande;
import GUI_GestionClient.ListerClients;
import GUI_Produit.VisualiserEtatProd;

import GUI_Produit.VisualiserEtatProd;

import java.awt.Color;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import static javax.swing.text.StyleConstants.FontFamily;

/**
 *
 * @author Yassine
 */
public class GenPDF extends javax.swing.JInternalFrame {

    /**
     * Creates new form interfaceProduit
     */
    
    Color setColor,resetColor;
    public GenPDF() {
        initComponents();
        this.setSize(1015,650);
        this.setBorder(createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);      
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpProd = new javax.swing.JDesktopPane();
        JPRIGHTadmin = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jGenPDF = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JPLEFTproduit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        VisEtatStock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VisClients = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        VisHistoCommande = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 745));

        JPRIGHTadmin.setBackground(new java.awt.Color(229, 229, 250));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\yderi\\Desktop\\CS\\Projet S6\\App_Gestion_Vente_Achat_V2\\src\\images\\return3.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Générer le rapport PDF");

        jGenPDF.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jGenPDF.setText("Générer le rapport");
        jGenPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenPDFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("N.B: Veuillez visiter chaque élément afin de pouvoir générer le PDF");

        javax.swing.GroupLayout JPRIGHTadminLayout = new javax.swing.GroupLayout(JPRIGHTadmin);
        JPRIGHTadmin.setLayout(JPRIGHTadminLayout);
        JPRIGHTadminLayout.setHorizontalGroup(
            JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                .addGroup(JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jGenPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        JPRIGHTadminLayout.setVerticalGroup(
            JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                .addGroup(JPRIGHTadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPRIGHTadminLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jGenPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpProd.setLayer(JPRIGHTadmin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpProdLayout = new javax.swing.GroupLayout(jdpProd);
        jdpProd.setLayout(jdpProdLayout);
        jdpProdLayout.setHorizontalGroup(
            jdpProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdpProdLayout.setVerticalGroup(
            jdpProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRIGHTadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPLEFTproduit.setBackground(new java.awt.Color(0, 204, 204));
        JPLEFTproduit.setPreferredSize(new java.awt.Dimension(227, 680));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu Produit");

        VisEtatStock.setBackground(new java.awt.Color(0, 204, 204));
        VisEtatStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisEtatStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisEtatStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisEtatStockMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Visualier l'état du stock");

        javax.swing.GroupLayout VisEtatStockLayout = new javax.swing.GroupLayout(VisEtatStock);
        VisEtatStock.setLayout(VisEtatStockLayout);
        VisEtatStockLayout.setHorizontalGroup(
            VisEtatStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisEtatStockLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VisEtatStockLayout.setVerticalGroup(
            VisEtatStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisEtatStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VisClients.setBackground(new java.awt.Color(0, 204, 204));
        VisClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisClientsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisClientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisClientsMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Visualiser la liste des clients");

        javax.swing.GroupLayout VisClientsLayout = new javax.swing.GroupLayout(VisClients);
        VisClients.setLayout(VisClientsLayout);
        VisClientsLayout.setHorizontalGroup(
            VisClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        VisClientsLayout.setVerticalGroup(
            VisClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        VisHistoCommande.setBackground(new java.awt.Color(0, 204, 204));
        VisHistoCommande.setPreferredSize(new java.awt.Dimension(160, 61));
        VisHistoCommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisHistoCommandeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisHistoCommandeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisHistoCommandeMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("<html><center><p>Visualiser l'historique<br/>des commandes</p></center></html>");

        javax.swing.GroupLayout VisHistoCommandeLayout = new javax.swing.GroupLayout(VisHistoCommande);
        VisHistoCommande.setLayout(VisHistoCommandeLayout);
        VisHistoCommandeLayout.setHorizontalGroup(
            VisHistoCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisHistoCommandeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VisHistoCommandeLayout.setVerticalGroup(
            VisHistoCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPLEFTproduitLayout = new javax.swing.GroupLayout(JPLEFTproduit);
        JPLEFTproduit.setLayout(JPLEFTproduitLayout);
        JPLEFTproduitLayout.setHorizontalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VisHistoCommande, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGroup(JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VisEtatStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPLEFTproduitLayout.setVerticalGroup(
            JPLEFTproduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLEFTproduitLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(VisEtatStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisHistoCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLEFTproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdpProd))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpProd)
            .addComponent(JPLEFTproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisClientsMouseClicked
    VisClients.setBackground(new Color(0,153,153));       
        jdpProd.add(new ListerClients()).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_VisClientsMouseClicked

    private void VisClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisClientsMouseExited
        VisClients.setBackground(new Color(0,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_VisClientsMouseExited

    private void VisHistoCommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisHistoCommandeMouseClicked
    VisHistoCommande.setBackground(new Color(0,153,153));     
        jdpProd.add(new adminVisualiserCommande()).setVisible(true);// TODO add your handling code here:        
         
    }//GEN-LAST:event_VisHistoCommandeMouseClicked

    private void VisHistoCommandeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisHistoCommandeMouseExited
     VisHistoCommande.setBackground(new Color(0,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_VisHistoCommandeMouseExited

    private void VisClientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisClientsMouseEntered
     VisClients.setBackground(new Color(0,204,153));         // TODO add your handling code here:
    }//GEN-LAST:event_VisClientsMouseEntered

    private void VisHistoCommandeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisHistoCommandeMouseEntered
    VisHistoCommande.setBackground(new Color(0,204,153));         // TODO add your handling code here:
    }//GEN-LAST:event_VisHistoCommandeMouseEntered

    private void VisEtatStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisEtatStockMouseExited
        VisEtatStock.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_VisEtatStockMouseExited

    private void VisEtatStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisEtatStockMouseEntered

        VisEtatStock.setBackground(new Color(0,204,153));

    }//GEN-LAST:event_VisEtatStockMouseEntered

    private void VisEtatStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisEtatStockMouseClicked
        VisEtatStock.setBackground(new Color(0,153,153));     
        jdpProd.add(new VisualiserEtatProd()).setVisible(true);
    }//GEN-LAST:event_VisEtatStockMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        try {
            this.setVisible(false);
            new AdminGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GenPDF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GenPDF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jGenPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenPDFActionPerformed
        String path="";
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int x =jfc.showSaveDialog(this);
        if( x == JFileChooser.APPROVE_OPTION){
            path = jfc.getSelectedFile().getPath();
        }
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+".pdf"));
            doc.open();
                    
            doc.add(new Paragraph("\n"));
                Paragraph p = new Paragraph("La liste des produits",FontFactory.getFont(FontFactory.TIMES_ROMAN,18, Font.BOLD));
                p.setAlignment(Element.ALIGN_CENTER);
            doc.add(p);
            doc.add(new Paragraph("\n"));
            
            PdfPTable tblProd = new PdfPTable(7);
            tblProd.setWidthPercentage(105);
            
            tblProd.addCell("ID");
            tblProd.addCell("Nom du produit");
            tblProd.addCell("Prix Unitaire");
            tblProd.addCell("Quantité");
            tblProd.addCell("Date d'entré");
            tblProd.addCell("Date de sortie");
            tblProd.addCell("Description");

            for(int i =0; i<VisualiserEtatProd.jtable.getRowCount();i++){
                String ID = VisualiserEtatProd.jtable.getValueAt(i, 0).toString();
                String nomProd = VisualiserEtatProd.jtable.getValueAt(i, 1).toString();
                String PU = VisualiserEtatProd.jtable.getValueAt(i, 2).toString();
                String QTE = VisualiserEtatProd.jtable.getValueAt(i, 3).toString();
                String dateEntre = VisualiserEtatProd.jtable.getValueAt(i, 4).toString();
                String dateSortie = VisualiserEtatProd.jtable.getValueAt(i, 5).toString();
                String Desc = VisualiserEtatProd.jtable.getValueAt(i, 6).toString();

                tblProd.addCell(ID);
                tblProd.addCell(nomProd);
                tblProd.addCell(PU);
                tblProd.addCell(QTE);
                tblProd.addCell(dateEntre);
                tblProd.addCell(dateSortie);
                tblProd.addCell(Desc);

            }

            doc.add(tblProd);
            
                ////////////////////////////////////////
                
            //CLIENTS
            doc.add(new Paragraph("\n"));
                Paragraph p2 = new Paragraph("La liste des clients",FontFactory.getFont(FontFactory.TIMES_ROMAN,18, Font.BOLD));
                p2.setAlignment(Element.ALIGN_CENTER);
            doc.add(p2);
            doc.add(new Paragraph("\n"));
            PdfPTable tblClient = new PdfPTable(2);
            tblClient.addCell("ID du client");
            tblClient.addCell("Login du client");
            
            for(int i =0; i<ListerClients.jtable.getRowCount();i++){
                String ID = ListerClients.jtable.getValueAt(i, 0).toString();
                String nomProd = ListerClients.jtable.getValueAt(i, 1).toString();
                
                tblClient.addCell(ID);
                tblClient.addCell(nomProd);
                
            }
                doc.add(tblClient);
                
                //////////////////////////////////////////
                
                //COMMANDE
                doc.add(new Paragraph("\n"));
                Paragraph p3 = new Paragraph("La liste des commandes",FontFactory.getFont(FontFactory.TIMES_ROMAN,18, Font.BOLD));
                p3.setAlignment(Element.ALIGN_CENTER);
            doc.add(p3);
            doc.add(new Paragraph("\n"));
            PdfPTable tblCommande = new PdfPTable(8);
            
            tblCommande.setWidthPercentage(105);
            
            tblCommande.addCell("ID Produit");
            tblCommande.addCell("ID Client");
            tblCommande.addCell("ID Commande");
            tblCommande.addCell("nom Commande");
            tblCommande.addCell("Date Commande");
            tblCommande.addCell("Qté commandée");
            tblCommande.addCell("nom du client");
            tblCommande.addCell("Prix Total");

            for(int i =0; i< adminVisualiserCommande.jtable.getRowCount();i++){
                
                String idProd = adminVisualiserCommande.jtable.getValueAt(i, 0).toString();
                String idClient = adminVisualiserCommande.jtable.getValueAt(i, 1).toString();
                String idCommande = adminVisualiserCommande.jtable.getValueAt(i, 2).toString();
                String nomCommande = adminVisualiserCommande.jtable.getValueAt(i, 3).toString();
                String dateCommande = adminVisualiserCommande.jtable.getValueAt(i, 4).toString();
                String qteCommande = adminVisualiserCommande.jtable.getValueAt(i, 5).toString();
                String nomClient = adminVisualiserCommande.jtable.getValueAt(i, 6).toString();
                String PrixTotal = adminVisualiserCommande.jtable.getValueAt(i, 7).toString();

                tblCommande.addCell(idProd);
                tblCommande.addCell(idClient);
                tblCommande.addCell(idCommande);
                tblCommande.addCell(nomCommande);
                tblCommande.addCell(dateCommande);
                tblCommande.addCell(qteCommande);
                tblCommande.addCell(nomClient);
                tblCommande.addCell(PrixTotal);

            }

            doc.add(tblCommande);

        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (DocumentException ex) {
            ex.printStackTrace();
        }

        doc.close();
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLEFTproduit;
    private javax.swing.JPanel JPRIGHTadmin;
    private javax.swing.JPanel VisClients;
    private javax.swing.JPanel VisEtatStock;
    private javax.swing.JPanel VisHistoCommande;
    private javax.swing.JButton jGenPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDesktopPane jdpProd;
    // End of variables declaration//GEN-END:variables
}
